version: '3.4'

services:
    api:
        image: blackwatch-api
        restart: always
        build:
            context: .
            dockerfile: ./BlackWatch.Api.Dockerfile
        ports:
            - "6000:5000"
            - "6001:5001"
        depends_on:
            - cache
        environment:
            - Redis__ConnectionString=cache:6379
    daemon:
        image: blackwatch-daemon
        restart: always
        build:
            context: .
            dockerfile: ./BlackWatch.Daemon.Dockerfile
        depends_on:
            - cache
        environment:
            - Redis__ConnectionString=cache:6379,abortConnect=false
            - Polygon__ApiKey=${POLYGON_API_KEY}
    cache:
        image: redis:6.2.6-alpine
        restart: always
        command: redis-server --save 60 1 --loglevel warning
        volumes:
            - ./redis-data:/data
