version: '3.4'

services:
    api:
        image: blackwatch-api
        restart: always
        build:
            context: ./BlackWatch.Api
            dockerfile: ./Dockerfile
        ports:
            - 6000:6000
        depends_on:
            - cache
    daemon:
        image: blackwatch-daemon
        restart: always
        build:
            context: ./BlackWatch.Daemon
            dockerfile: ./Dockerfile
        depends_on:
            - cache
    cache:
        image: redis-6.2.6-alpine
        restart: always
        command: redis-server --save 60 1 --loglevel warning
        volumes:
            ./redis-data:/data
