version: '3.4'

services:
    api:
        image: blackwatch-api
        build:
            context: .
            dockerfile: ./BlackWatch.Api.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - ~/.vsdbg:/remote_debugger:rw
        ports:
            - "6000:5000"
        depends_on:
            - cache
    daemon:
        image: blackwatch-daemon
        build:
            context: .
            dockerfile: ./BlackWatch.Daemon.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - Redis__ConnectionString=cache:6379
        volumes:
            - ~/.vsdbg:/remote_debugger:rw
        depends_on:
            - cache
    cache:
        image: redis:6.2.6-alpine
        restart: always
        command: redis-server --save 60 1 --loglevel warning
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data
