version: '3.4'

services:
    webapp:
        image: blackwatch-webapp
        restart: always
        build:
            context: .
            dockerfile: ./BlackWatch.WebApp.Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ${PWD}/src/BlackWatch.WebApp/wwwroot/appsettings.json:/usr/local/webapp/nginx/html/appsettings.json:ro
        depends_on:
            - api
    api:
        image: blackwatch-api
        restart: always
        build:
            context: .
            dockerfile: ./BlackWatch.Api.Dockerfile
        ports:
            - "8667:5000"
        depends_on:
            - cache
        environment:
            - Redis__ConnectionString=cache:6379
    daemon:
        image: blackwatch-daemon
        restart: always
        build:
            context: .
            dockerfile: ./BlackWatch.Daemon.Dockerfile
        depends_on:
            - cache
        environment:
            - Redis__ConnectionString=cache:6379,abortConnect=false
            - Polygon__ApiKey=${POLYGON_API_KEY}
    cache:
        image: redis:6.2.6-alpine
        restart: always
        command: redis-server --save 60 1 --loglevel warning
        volumes:
            - ./redis-data:/data
